// Generated by gencpp from file imusensor/ImuEvent.msg
// DO NOT EDIT!


#ifndef IMUSENSOR_MESSAGE_IMUEVENT_H
#define IMUSENSOR_MESSAGE_IMUEVENT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <imusensor/AccelGyro.h>

namespace imusensor
{
template <class ContainerAllocator>
struct ImuEvent_
{
  typedef ImuEvent_<ContainerAllocator> Type;

  ImuEvent_()
    : time()
    , seqNum(0)
    , imuId(0)
    , data()  {
    }
  ImuEvent_(const ContainerAllocator& _alloc)
    : time()
    , seqNum(0)
    , imuId(0)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef ros::Time _time_type;
  _time_type time;

   typedef uint8_t _seqNum_type;
  _seqNum_type seqNum;

   typedef uint8_t _imuId_type;
  _imuId_type imuId;

   typedef  ::imusensor::AccelGyro_<ContainerAllocator>  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::imusensor::ImuEvent_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::imusensor::ImuEvent_<ContainerAllocator> const> ConstPtr;

}; // struct ImuEvent_

typedef ::imusensor::ImuEvent_<std::allocator<void> > ImuEvent;

typedef boost::shared_ptr< ::imusensor::ImuEvent > ImuEventPtr;
typedef boost::shared_ptr< ::imusensor::ImuEvent const> ImuEventConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::imusensor::ImuEvent_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::imusensor::ImuEvent_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::imusensor::ImuEvent_<ContainerAllocator1> & lhs, const ::imusensor::ImuEvent_<ContainerAllocator2> & rhs)
{
  return lhs.time == rhs.time &&
    lhs.seqNum == rhs.seqNum &&
    lhs.imuId == rhs.imuId &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::imusensor::ImuEvent_<ContainerAllocator1> & lhs, const ::imusensor::ImuEvent_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace imusensor

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::imusensor::ImuEvent_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::imusensor::ImuEvent_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::imusensor::ImuEvent_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::imusensor::ImuEvent_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imusensor::ImuEvent_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imusensor::ImuEvent_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::imusensor::ImuEvent_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0fe43237e9123a79e97b4f36de9d49e4";
  }

  static const char* value(const ::imusensor::ImuEvent_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0fe43237e9123a79ULL;
  static const uint64_t static_value2 = 0xe97b4f36de9d49e4ULL;
};

template<class ContainerAllocator>
struct DataType< ::imusensor::ImuEvent_<ContainerAllocator> >
{
  static const char* value()
  {
    return "imusensor/ImuEvent";
  }

  static const char* value(const ::imusensor::ImuEvent_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::imusensor::ImuEvent_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time time\n"
"uint8 seqNum\n"
"uint8 imuId\n"
"AccelGyro data\n"
"\n"
"================================================================================\n"
"MSG: imusensor/AccelGyro\n"
"float32[3] accel\n"
"float32[3] gyro\n"
;
  }

  static const char* value(const ::imusensor::ImuEvent_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::imusensor::ImuEvent_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.time);
      stream.next(m.seqNum);
      stream.next(m.imuId);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImuEvent_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::imusensor::ImuEvent_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::imusensor::ImuEvent_<ContainerAllocator>& v)
  {
    s << indent << "time: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.time);
    s << indent << "seqNum: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.seqNum);
    s << indent << "imuId: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.imuId);
    s << indent << "data: ";
    s << std::endl;
    Printer< ::imusensor::AccelGyro_<ContainerAllocator> >::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IMUSENSOR_MESSAGE_IMUEVENT_H
